var KI4SO_SERVER_EC ="KI4SO_SERVER_EC";//登陆EC
var PLATFORM_USER_OBJ ="PLATFORM_USER_OBJ";//用户对象
var PLATFORM_USER_ID ="PLATFORM_USER_ID";//用户ID
var PLATFORM_RESOURCE_CODES ="PLATFORM_RESOURCE_CODES";//用户权限code
var STORE_BUY_GOODS ="STORE_BUY_GOODS";//购买物品
var STORE_BUY_TOTAL_PRICE = "STORE_BUY_TOTAL_PRICE";//购买物品总价

module.exports.KI4SO_SERVER_EC = KI4SO_SERVER_EC;
module.exports.PLATFORM_USER_OBJ = PLATFORM_USER_OBJ;
module.exports.PLATFORM_USER_ID = PLATFORM_USER_ID;
module.exports.PLATFORM_RESOURCE_CODES = PLATFORM_RESOURCE_CODES;
module.exports.STORE_BUY_GOODS = STORE_BUY_GOODS;
module.exports.STORE_BUY_TOTAL_PRICE = STORE_BUY_TOTAL_PRICE;